---

- hosts: server1
  become: true
  tasks:
          - name: update repository index
            apt:
                  update_cache: yes


          - name: install apache2
            apt:
                    name: apache2
                    state: absent

          - name: add php support to apache2
            apt:
                    name: libapache2-mod-php
                    state: absent

