---

- hosts: all
  become: true
  tasks:

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php for Ubuntu servers
    tags: apache2,ubuntu
    apt:
      name: 
        - apache2
        - php5
        - libapache2-mod-php5
        - php5-mcrypt
        - php5-cli
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for Centos servers
    tags: httpd,centos
    apt:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CenOS"

  - name: change e-mail address for admin
    tags: apache, apache2,httpd
    lineinfile:
      path: /etc/http/conf
      regexp: '^ServerAdmin'
      line: ServerAdmin  hamid@unimatel.ma
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: restart httpd (CentOS)
    tags: apache, httpd,centos
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for site
    tags: apache2,httpd,copie
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos, db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    tags: ubuntu, db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu" 

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest




